name: nyxx_commander
version: 1.1.0-dev.1
description: A Discord library for Dart.
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.12.0-51.0.dev <3.0.0'

dependencies:
  nyxx: "^1.1.0-dev.1"
  logging: "^1.0.0-nullsafety.0"

dependency_overrides:
  http:
    git:
      url: git://github.com/dart-lang/http.git
  http_parser:
    git:
      url: git://github.com/dart-lang/http_parser.git
  nyxx:
    path: "../nyxx"
