name: nyxx
version: 1.1.0-dev.2
description: A Discord library for Dart.
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.12.0-51.0.dev <3.0.0'

dependencies:
  logging: "^1.0.0-nullsafety.0"
  http: "0.13.0"
  path: "^1.8.0-nullsafety.3"
