name: nyxx
version: 1.1.0-dev.5
description: A Discord library for Dart.
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.12.0 <2.13.0'

dependencies:
  http: "^0.13.0"
  logging: "^1.0.1"
  path: "^1.8.0"

dev_dependencies:
  test: "^1.16.8"
