name: nyxx
version: 1.0.0
description: A Discord library for Dart.
authors:
- Szymon Uglis <szymon.uglis@tuta.io>
- Zach Vacura <admin@hackzzila.com>
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.8.0-dev.15.0 <3.0.0'

dependencies:
  logging: "^0.11.4"
  w_transport: "^3.2.8"

dev_dependencies:
  dart_style:
  analyzer:
