name: nyxx_interactions
version: 2.0.0-rc.6
description: Nyxx Interactions Module. Discord library for Dart. Simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: "^1.0.1"
  nyxx: "2.0.0-rc.5"
